### ISSUE TITLE
Error on importing library

### ISSUE THREAD

**Issue by truongnmt** [analysiscenter/cardio#11]
I'm importing libraries in this tutorial [Dirichlet model training for Atrial fibrillation detection](https://github.com/analysiscenter/cardio/blob/master/cardio/models/dirichlet_model/dirichlet_model_training.ipynb), on importing Dirichlet model:
```python
from cardio.models.dirichlet_model import DirichletModel, concatenate_ecg_batch
```
I got this error:
`
AttributeError: module 'tensorflow.python.ops.losses.losses' has no attribute 'huber_loss'
`

My environment:
Anaconda Python 3.6.5
Tensorflow 1.1.0
Mac Sierra 10.12

**Comment by roman-kh** [comment]
Cardio is based on [Dataset](https://github.com/analysiscenter/dataset) which requires TensorFlow 1.4 or higher.
