### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by eigen2017** [analysiscenter/cardio#13]
python setup.py install

running install
running bdist_egg
running egg_info
writing requirements to cardio.egg-info/requires.txt
writing cardio.egg-info/PKG-INFO
writing top-level names to cardio.egg-info/top_level.txt
writing dependency_links to cardio.egg-info/dependency_links.txt
reading manifest file 'cardio.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.git' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '#*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
writing manifest file 'cardio.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/cardio
creating build/bdist.linux-x86_64/egg/cardio/pipelines
copying build/lib/cardio/pipelines/pipelines.py -> build/bdist.linux-x86_64/egg/cardio/pipelines
copying build/lib/cardio/pipelines/__init__.py -> build/bdist.linux-x86_64/egg/cardio/pipelines
creating build/bdist.linux-x86_64/egg/cardio/core
copying build/lib/cardio/core/ecg_batch_tools.py -> build/bdist.linux-x86_64/egg/cardio/core
copying build/lib/cardio/core/kernels.py -> build/bdist.linux-x86_64/egg/cardio/core
copying build/lib/cardio/core/ecg_dataset.py -> build/bdist.linux-x86_64/egg/cardio/core
copying build/lib/cardio/core/utils.py -> build/bdist.linux-x86_64/egg/cardio/core
copying build/lib/cardio/core/__init__.py -> build/bdist.linux-x86_64/egg/cardio/core
copying build/lib/cardio/core/ecg_batch.py -> build/bdist.linux-x86_64/egg/cardio/core
creating build/bdist.linux-x86_64/egg/cardio/models
copying build/lib/cardio/models/keras_custom_objects.py -> build/bdist.linux-x86_64/egg/cardio/models
creating build/bdist.linux-x86_64/egg/cardio/models/dirichlet_model
copying build/lib/cardio/models/dirichlet_model/dirichlet_model.py -> build/bdist.linux-x86_64/egg/cardio/models/dirichlet_model
copying build/lib/cardio/models/dirichlet_model/__init__.py -> build/bdist.linux-x86_64/egg/cardio/models/dirichlet_model
copying build/lib/cardio/models/layers.py -> build/bdist.linux-x86_64/egg/cardio/models
creating build/bdist.linux-x86_64/egg/cardio/models/fft_model
copying build/lib/cardio/models/fft_model/fft_model.py -> build/bdist.linux-x86_64/egg/cardio/models/fft_model
copying build/lib/cardio/models/fft_model/__init__.py -> build/bdist.linux-x86_64/egg/cardio/models/fft_model
creating build/bdist.linux-x86_64/egg/cardio/models/hmm
copying build/lib/cardio/models/hmm/hmm.py -> build/bdist.linux-x86_64/egg/cardio/models/hmm
copying build/lib/cardio/models/hmm/__init__.py -> build/bdist.linux-x86_64/egg/cardio/models/hmm
copying build/lib/cardio/models/metrics.py -> build/bdist.linux-x86_64/egg/cardio/models
copying build/lib/cardio/models/__init__.py -> build/bdist.linux-x86_64/egg/cardio/models
copying build/lib/cardio/__init__.py -> build/bdist.linux-x86_64/egg/cardio
byte-compiling build/bdist.linux-x86_64/egg/cardio/pipelines/pipelines.py to pipelines.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/pipelines/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/core/ecg_batch_tools.py to ecg_batch_tools.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/core/kernels.py to kernels.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/core/ecg_dataset.py to ecg_dataset.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/core/utils.py to utils.pyc
  File "build/bdist.linux-x86_64/egg/cardio/core/utils.py", line 30
    return func(self, *frozen_args, *args, **frozen_kwargs, **kwargs)
                                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/cardio/core/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/core/ecg_batch.py to ecg_batch.pyc
  File "build/bdist.linux-x86_64/egg/cardio/core/ecg_batch.py", line 26
    "idwt": (lambda x, *args, **kwargs: pywt.idwt(*x, *args, **kwargs), "pywt.idwt",
                                                      ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/cardio/models/keras_custom_objects.py to keras_custom_objects.pyc
  File "build/bdist.linux-x86_64/egg/cardio/models/keras_custom_objects.py", line 202
    return (*input_shape[:-1], self.base_dim + 3 * self.nb_filters)
            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/cardio/models/dirichlet_model/dirichlet_model.py to dirichlet_model.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/dirichlet_model/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/layers.py to layers.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/fft_model/fft_model.py to fft_model.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/fft_model/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/hmm/hmm.py to hmm.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/hmm/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/metrics.py to metrics.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/models/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cardio/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cardio.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cardio.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cardio.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cardio.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cardio.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cardio.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/cardio-0.2.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cardio-0.2.0-py2.7.egg
removing '/usr/lib/python2.7/site-packages/cardio-0.2.0-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/cardio-0.2.0-py2.7.egg
Extracting cardio-0.2.0-py2.7.egg to /usr/lib/python2.7/site-packages
  File "/usr/lib/python2.7/site-packages/cardio-0.2.0-py2.7.egg/cardio/core/utils.py", line 30
    return func(self, *frozen_args, *args, **frozen_kwargs, **kwargs)
                                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python2.7/site-packages/cardio-0.2.0-py2.7.egg/cardio/core/ecg_batch.py", line 26
    "idwt": (lambda x, *args, **kwargs: pywt.idwt(*x, *args, **kwargs), "pywt.idwt",
                                                      ^
SyntaxError: invalid syntax

  File "/usr/lib/python2.7/site-packages/cardio-0.2.0-py2.7.egg/cardio/models/keras_custom_objects.py", line 202
    return (*input_shape[:-1], self.base_dim + 3 * self.nb_filters)
            ^
SyntaxError: invalid syntax

cardio 0.2.0 is already the active version in easy-install.pth

Installed /usr/lib/python2.7/site-packages/cardio-0.2.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    'Topic :: Scientific/Engineering'
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by roman-kh** [comment]
`CardIO` supports python 3.5 or higher.
https://github.com/analysiscenter/cardio#installation
