### ISSUE TITLE
Errors on running tutorials

### ISSUE THREAD

**Issue by andrii-fadieiev** [analysiscenter/cardio#24]
Hello
I'm getting errors running Tutorials notebooks.

In Notebook 2 (Pipelines) I got this
![Screenshot from 2019-05-04 11-43-34](https://user-images.githubusercontent.com/537693/57176553-028a9e00-6e62-11e9-9fd9-c3d8a8c1902f.png)

And in Notebook 3 (Models) I got this error
![Screenshot from 2019-05-04 11-46-33](https://user-images.githubusercontent.com/537693/57176597-6a40e900-6e62-11e9-9f43-ecacfbd5f9cd.png)

I'm using Ubuntu 18.04 with latest anaconda

**Comment by dpodvyaznikov** [comment]
Hi!
It seems that there is no data in folders specified by `PATH_TO_DATA` (notebook 2) and `SIGNALS_PATH` (notebook 3).
Please, check that you've downloaded datasets mentioned in tutorials: [CinC17](https://physionet.org/challenge/2017/) and [QT Database](https://www.physionet.org/physiobank/database/qtdb/). 
If you already have the data, change path constants accordingly.

**Comment by andrii-fadieiev** [comment]
Hello there!
That was helpful :) Was a bit confused with that error messages.
Thank you for your help and amazing library!
