### ISSUE TITLE
ModuleNotFoundError: No module named 'cardio.dataset'

### ISSUE THREAD

**Issue by kobeHub** [analysiscenter/cardio#25]
I get `ModuleNotFoundError: No module named 'cardio.dataset'`, when I try to `import cardio.dataset as ds`. I install cardio via pip and git repository, but none works. 
I use python3.7.3

**Comment by roman-kh** [comment]
`dataset` submodule has been renamed to `batchflow`, so try this: `import cardio.batchflow as ds`

**Comment by kobeHub** [comment]
Thank a lot!
