### ISSUE TITLE
GMM in scikit-learn deprecation 0.19.1

### ISSUE THREAD

**Issue by lkjell** [analysiscenter/cardio#26]
setup.py should pin to version 0.19.1 and not accept version above 0.20 as GMM module is removed [1]. Else the new module should be adapted.

https://scikit-learn.org/0.18/modules/generated/sklearn.mixture.GMM.html#sklearn.mixture.GMM

**Comment by roman-kh** [comment]
@dpodvyaznikov @alexandrkuvaev Guys, please, make a PR

**Comment by roman-kh** [comment]
Solved in #27
