### ISSUE TITLE
Installation Failed ( pyEDFlib requires a version of NumPy, even for setup )

### ISSUE THREAD

**Issue by Shlyankin** [analysiscenter/cardio#28]
Привет. Не получается установить библиотеку cardIO. Пробовал устанавливать через pipenv, pip и через python setup.py install. В всех случаях ругается на pyEDFlib и NumPy.
Лог прилагается.

Hello. I am having a problem installing the cardIO library using pipenv or pip. Maybe the problem is in setup.py or pyEDFlib?

It is log:
Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\user>pipenv install git+https://github.com/analysiscenter/cardio.git#eg
g=cardio
Creating a virtualenv for this project:
Pipfile: C:\Users\user\Pipfile
Using c:\python\python.exe (3.7.4) to create virtualenv:
[ =] Creating virtual environment...Already using interpreter c:\python\python
.exe
Using base prefix 'c:\python'
New python executable in C:\Users\user.virtualenvs\user-KgVmIwbj\Scripts\python
.exe
Installing setuptools, pip, wheel...
done.

Successfully created virtual environment!
Virtualenv location: C:\Users\user.virtualenvs\user-KgVmIwbj
Creating a Pipfile for this project:
Installing git+https://github.com/analysiscenter/cardio.git#egg=cardio:
Warning: You installed a VCS dependency in non-editable mode. This will work fin
e, but sub-dependencies will not be resolved by $ pipenv lock.
To enable this sub-dependency functionality, specify that this dependency is e
ditable.
Collecting cardio from git+https://github.com/analysiscenter/cardio.git#egg=card
io
Cloning https://github.com/analysiscenter/cardio.git to c:\users\user\appdata
local\temp\pip-install-g2sfymp2\cardio
Collecting numpy>=1.13.1 (from cardio)
Downloading https://files.pythonhosted.org/packages/26/26/73ba03b2206371cdef62
afebb877e9ba90a1f0dc3d9de22680a3970f5a50/numpy-1.17.0-cp37-cp37m-win_amd64.whl (
12.8MB)
Collecting scipy>=0.19.1 (from cardio)
Downloading https://files.pythonhosted.org/packages/50/eb/defa40367863304e1ef0
1c6572584c411446a5f29bdd9dc90f91509e9144/scipy-1.3.1-cp37-cp37m-win_amd64.whl (3
0.3MB)
Collecting pandas>=0.21.1 (from cardio)
Downloading https://files.pythonhosted.org/packages/c1/cf/58ccaa38d5670dd4d2ae
e5df90aa03d670ede3947b7148e72391c80d4f91/pandas-0.25.0-cp37-cp37m-win_amd64.whl
(9.2MB)
Collecting scikit-learn==0.19.1 (from cardio)
Downloading https://files.pythonhosted.org/packages/f5/2c/5edf2488897cad4fb8c4
ace86369833552615bf264460ae4ef6e1f258982/scikit-learn-0.19.1.tar.gz (9.5MB)
Collecting numba>=0.35.0 (from cardio)
Downloading https://files.pythonhosted.org/packages/dd/89/861d76f7a677fc5ba7fa
fa8085017c43b76e3880e9e365f863f8cc800a46/numba-0.45.1-cp37-cp37m-win_amd64.whl (
2.0MB)
Collecting pywavelets>=0.5.2 (from cardio)
Downloading https://files.pythonhosted.org/packages/71/57/1b6c06f2b681975e5b43
ff13ba127031f668d65b592cc56fae6445b675c7/PyWavelets-1.0.3-cp37-none-win_amd64.wh
l (4.2MB)
Collecting matplotlib>=2.1.0 (from cardio)
Downloading https://files.pythonhosted.org/packages/1a/c0/69e3f695d7384012e90b
e1e16570c08953baae00fd98094179ef87c7d5a2/matplotlib-3.1.1-cp37-cp37m-win_amd64.w
hl (9.1MB)
Collecting dill>=0.2.7.1 (from cardio)
Downloading https://files.pythonhosted.org/packages/39/7a/70803635c850e3512570
29089d38748516a280864c97cbc73087afef6d51/dill-0.3.0.tar.gz (151kB)
Collecting pydicom>=0.9.9 (from cardio)
Downloading https://files.pythonhosted.org/packages/fc/d5/da1fdf3b967e324ee47a
7ad9553c9b94c1193b6b98afd9eeda0efb76b9f7/pydicom-1.3.0-py2.py3-none-any.whl (7.1
MB)
Collecting pyedflib>=0.1.11 (from cardio)
Downloading https://files.pythonhosted.org/packages/a4/c1/11d90aa4d20a1d3df04e
a9e1db4e03fea4b199a5b515a057cbe5e35769c0/pyEDFlib-0.1.14.tar.gz (1.1MB)

Error: An error occurred while installing git+https://github.com/analysiscenter
/cardio.git#egg=cardio!
b' Running command git clone -q https://github.com/analysiscenter/cardio.git '
C:\Users\user\AppData\Local\Temp\pip-install-g2sfymp2\cardio'\n Running
command git submodule update --init --recursive -q\n ERROR: Command errored
out with exit status 4294967295:\n command: 'c:\users\user\.virtualenvs
\user-kgvmiwbj\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys
.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-instal
l-g2sfymp2\\pyedflib\\setup.py'"'"'; file='"'"'C:\\Users\\user
\\AppData\\Local\\Temp\\pip-install-g2sfymp2\\pyedflib\\setup.py'"
'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().rep
lace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, _
file_, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info\n cwd
: C:\Users\user\AppData\Local\Temp\pip-install-g2sfymp2\pyedflib\\n C
omplete output (4 lines):\n No module named 'numpy'\n *** package "numpy
" not found ***\n pyEDFlib requires a version of NumPy, even for setup.\n
Please get it from http://numpy.scipy.org/ or install it through your package ma
nager.\n ----------------------------------------\nERROR: Command errored out
with exit status 4294967295: python setup.py egg_info Check the logs for full c
ommand output.\n'
This is likely caused by a bug in cardio. Report this to its maintainers.
Installation Failed

**Comment by roman-kh** [comment]
Apparently the problem has nothing to do with `cardio` on its own. 
The thing is that you don't have `numpy` installed while it's required by `pyedflib`.
The question "why python tries to install `pyedflib` before `numpy`" is a notorious example of questions hardy ever answered as there is a long-existing problem with a weird install order (e.g. https://github.com/pypa/pip/issues/24).

As a workaround, install `numpy` first, then install `cardio`.

**Comment by Shlyankin** [comment]
@roman-kh , 
I already have `numpy`. I think problem in the python version. I installed `python 3.6.1` (instead of `3.7.4`) and downloaded `cardio` using `pipenv`. It seems to work.

From this post https://github.com/holgern/pyedflib/issues/60, I think that `pyEDFlib` have not binaries files for `python 3.7`.
