### ISSUE TITLE
pipenv installation doesn't work

### ISSUE THREAD

**Issue by gsm2055** [analysiscenter/cardio#29]
Microsoft Windows [Version 10.0.18362.295]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\gsm20>pip install cardio
Collecting cardio
  ERROR: Could not find a version that satisfies the requirement cardio (from versions: none)
ERROR: No matching distribution found for cardio

C:\Users\gsm20>pipenv install git+https://github.com/analysiscenter/cardio.git#egg=cardio
Installing git+https://github.com/analysiscenter/cardio.git#egg=cardio…
Warning: You installed a VCS dependency in non-editable mode. This will work fine, but sub-dependencies will not be resolved by $ pipenv lock.
  To enable this sub-dependency functionality, specify that this dependency is editable.
Collecting cardio from git+https://github.com/analysiscenter/cardio.git#egg=cardio
  Cloning https://github.com/analysiscenter/cardio.git to c:\users\gsm20\appdata\local\temp\pip-install-r0n92tbz\cardio
Collecting numpy>=1.13.1 (from cardio)
  Downloading https://files.pythonhosted.org/packages/cb/41/05fbf6944b098eb9d53e8a29a9dbfa20a7448f3254fb71499746a29a1b2d/numpy-1.17.1-cp37-cp37m-win_amd64.whl (12.8MB)
Collecting scipy>=0.19.1 (from cardio)
  Using cached https://files.pythonhosted.org/packages/50/eb/defa40367863304e1ef01c6572584c411446a5f29bdd9dc90f91509e9144/scipy-1.3.1-cp37-cp37m-win_amd64.whl
Collecting pandas>=0.21.1 (from cardio)
  Using cached https://files.pythonhosted.org/packages/b1/69/fcc29820befae2b96fd0b01225577af653e87cd0914634bb2d372a457bd7/pandas-0.25.1-cp37-cp37m-win_amd64.whl
Collecting scikit-learn==0.19.1 (from cardio)
  Using cached https://files.pythonhosted.org/packages/f5/2c/5edf2488897cad4fb8c4ace86369833552615bf264460ae4ef6e1f258982/scikit-learn-0.19.1.tar.gz
Collecting numba>=0.35.0 (from cardio)
  Using cached https://files.pythonhosted.org/packages/dd/89/861d76f7a677fc5ba7fafa8085017c43b76e3880e9e365f863f8cc800a46/numba-0.45.1-cp37-cp37m-win_amd64.whl
Collecting pywavelets>=0.5.2 (from cardio)
  Using cached https://files.pythonhosted.org/packages/71/57/1b6c06f2b681975e5b43ff13ba127031f668d65b592cc56fae6445b675c7/PyWavelets-1.0.3-cp37-none-win_amd64.whl
Collecting matplotlib>=2.1.0 (from cardio)
  Using cached https://files.pythonhosted.org/packages/1a/c0/69e3f695d7384012e90be1e16570c08953baae00fd98094179ef87c7d5a2/matplotlib-3.1.1-cp37-cp37m-win_amd64.whl
Collecting dill>=0.2.7.1 (from cardio)
  Using cached https://files.pythonhosted.org/packages/39/7a/70803635c850e351257029089d38748516a280864c97cbc73087afef6d51/dill-0.3.0.tar.gz
Collecting pydicom>=0.9.9 (from cardio)
  Using cached https://files.pythonhosted.org/packages/fc/d5/da1fdf3b967e324ee47a7ad9553c9b94c1193b6b98afd9eeda0efb76b9f7/pydicom-1.3.0-py2.py3-none-any.whl
Collecting pyedflib>=0.1.11 (from cardio)
  Using cached https://files.pythonhosted.org/packages/a4/c1/11d90aa4d20a1d3df04ea9e1db4e03fea4b199a5b515a057cbe5e35769c0/pyEDFlib-0.1.14.tar.gz

Error:  An error occurred while installing git+https://github.com/analysiscenter/cardio.git#egg=cardio!
b'  Running command git clone -q https://github.com/analysiscenter/cardio.git \'C:\\Users\\gsm20\\AppData\\Local\\Temp\\pip-install-r0n92tbz\\cardio\'\n  Running command git submodule update --init --recursive -q\n    ERROR: Command errored out with exit status 4294967295:\n     command: \'c:\\users\\gsm20\\.virtualenvs\\gsm20-sprtm5uw\\scripts\\python.exe\' -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'C:\\\\Users\\\\gsm20\\\\AppData\\\\Local\\\\Temp\\\\pip-install-r0n92tbz\\\\pyedflib\\\\setup.py\'"\'"\'; __file__=\'"\'"\'C:\\\\Users\\\\gsm20\\\\AppData\\\\Local\\\\Temp\\\\pip-install-r0n92tbz\\\\pyedflib\\\\setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base pip-egg-info\n         cwd: C:\\Users\\gsm20\\AppData\\Local\\Temp\\pip-install-r0n92tbz\\pyedflib\\\n    Complete output (4 lines):\n    No module named \'numpy\'\n    *** package "numpy" not found ***\n    pyEDFlib requires a version of NumPy, even for setup.\n    Please get it from http://numpy.scipy.org/ or install it through your package manager.\n    ----------------------------------------\nERROR: Command errored out with exit status 4294967295: python setup.py egg_info Check the logs for full command output.\n'
This is likely caused by a bug in cardio. Report this to its maintainers.
Installation 

i am trying to install using cmd( i am using windows 10 and python3.7) 
but i get this error..

can you tell me why..? how can i fix it??

and can i use zip file and comman python setup.py install??

**Comment by roman-kh** [comment]
This has nothing to do with cardio. PeEDFlib doesn't have binaries for python 3.7.
See #28 for detail.

**Comment by gsm2055** [comment]
thx to your reply :) i solve it
