### ISSUE TITLE
syntax error when importing batch.py 

### ISSUE THREAD

**Issue by quzhouxiachuan** [analysiscenter/cardio#4]
`
import os  
import sys 
sys.path.append("..") 
import cardio.dataset as ds 
from cardio import EcgBatch 
from cardio.models.metrics import classification_report 
%env CUDA_VISIBLE_DEVICES=0 
import tensorflow as tf  
`
<br />
Error message as the following: 
<br />

User/ydee/anaconda2/lib/python2.7/site-packages/cardio/dataset/dataset/batch.py", line 403
    _args = tuple([src_attr, *args])
                             ^
SyntaxError: invalid syntax

**Comment by roman-kh** [comment]
CardIO supports python 3.5 or higher.

**Comment by roman-kh** [comment]
We moved python version check to the earlier stage, so the program should stop with a clear message that a newer python version is needed.

**Comment by quzhouxiachuan** [comment]
Thanks!
