### ISSUE TITLE
AttributeError: unstack_signals not found in class EcgBatch

### ISSUE THREAD

**Issue by quzhouxiachuan** [analysiscenter/cardio#8]
Hi 
I ran into errors when running I.Cardio tutorial file. The script before this works fine, could you help with that?

`original_batch = batch_with_data.deepcopy()
changed_batch = batch_with_data.deepcopy()

original_batch.random_split_signals(length=3000, n_segments=4)

changed_batch.random_split_signals(length=3000, n_segments=4).unstack_signals()`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-eb588bac5d56> in <module>()
      4 original_batch.random_split_signals(length=3000, n_segments=4)
      5 
----> 6 changed_batch.random_split_signals(length=3000, n_segments=4).unstack_signals()

~/anaconda3/lib/python3.6/site-packages/cardio/dataset/dataset/batch.py in __getattr__(self, name)
    258             return attr
    259         else:
--> 260             raise AttributeError("%s not found in class %s" % (name, self.__class__.__name__))
    261 
    262     def __setattr__(self, name, value):

AttributeError: unstack_signals not found in class EcgBatch

**Comment by alexanderkuvaev** [comment]
Hi!

Perhaps you use CardIO 0.1.0. The version number can be obtained by running the following commands:

```python
import cardio
print(cardio.__version__)
```

If that's the case, please, update the package to the latest version.

**Comment by quzhouxiachuan** [comment]
Hi

Just checked, my version is indeed 0.1.0. Also I have the following warnings: 

/Users/yd/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)

Should I be worried about this and update the version of tensorflow to 3.6?

Thanks!

**Comment by roman-kh** [comment]
The warning means that your tensorflow version does not match the python version for some reason.
Try to update the tensorflow package.

**Comment by quzhouxiachuan** [comment]
Thanks! Just updated both versions, it works fine now :)
